Add navigation
2gis/mobile-sdk-ios-demo pull request #155
Opened 2022-04-07 06:33 UTC by abersenev

2022-04-11 10:19 UTC, ktoto approved these changes

2022-04-13 15:25 UTC, ok-gurov requested changes

2022-04-13 15:25 UTC, ok-gurov commented on docs/ru/examples.md
> +// Создаём фабрику объектов карты
```suggestion
// Создаём фабрику объектов карты.
```
Можно в конце комментариев тоже точки добавить тут и ниже.

2022-04-14 08:46 UTC, abersenev commented on docs/ru/examples.md
> +// Создаём фабрику объектов карты
Добавил.

2022-04-15 09:41 UTC, ok-gurov commented on docs/en/examples.md
> +// Create a map object
```suggestion
// Create a map object.
```
Тут и ниже тоже бы добавить точки)

2022-04-15 09:45 UTC, ok-gurov commented on docs/ru/examples.md
> +navigationView.closeButtonCallback = {
Ой, тут плохой пример. Утечка будет. Так лучше
```suggestion
navigationView.closeButtonCallback = { [weak navigationManager] in
```

2022-04-15 09:47 UTC, ok-gurov requested changes

2022-04-15 09:47 UTC, ok-gurov commented on docs/ru/examples.md
> +    navigationManager.stop()
и потом так
```suggestion
    navigationManager?.stop()
```

2022-04-15 09:47 UTC, ok-gurov commented on docs/en/examples.md
> +navigationView.closeButtonCallback = {
```suggestion
navigationView.closeButtonCallback = { [weak navigationManager] in
```

2022-04-15 09:47 UTC, ok-gurov commented on docs/en/examples.md
> +    navigationManager.stop()
```suggestion
    navigationManager?.stop()
```

2022-04-18 06:52 UTC, abersenev commented on docs/en/examples.md
> +// Create a map object
Добавил во всех примерах.

2022-04-18 06:53 UTC, abersenev commented on docs/ru/examples.md
> +navigationView.closeButtonCallback = {
Исправил.

2022-04-18 07:04 UTC, ok-gurov approved these changes

2022-04-27 07:22 UTC, merged