Add Future and Channel examples
2gis/mobile-sdk-ios-demo pull request #18
Opened 2021-04-08 03:57 UTC by ok-gurov

2021-04-08 04:56 UTC, lagner commented on docs/en/examples.md
> +let sdk = PlatformSDK.Container(apiKeys: self.apiKeys)
Сейчас уже столкнулись что не очевидно что нужно руками выставлять PPI. Давай это тоже к инициализации добавим?
@aapng что думаешь?

2021-04-08 04:56 UTC, lagner commented on docs/en/examples.md
> +// получение объект справочника по идентификатору
либо "получаем", либо "объекта"

2021-04-08 04:56 UTC, lagner commented on docs/en/examples.md
> +let combineFuture = future.asCombineFuture()
Думаешь нужно это? Давай конечно оставим и потом документат на это просмотрит, но мне кажется такой пример был же уже

2021-04-08 04:56 UTC, lagner commented on docs/en/examples.md
> +self.cancellable = visibleRectChannel.sink { [weak self] visibleRect in
Мож добавим отдельно строчку что саму подписку надо сохранять, это же важно. На это кажется все наступают

2021-04-08 05:17 UTC, aapng commented on docs/en/examples.md
> +let sdk = PlatformSDK.Container(apiKeys: self.apiKeys)
Согласен, это важно. Нужно в разделе "создание карты", так как делается отдельным вызовом.

2021-04-08 09:25 UTC, ok-gurov commented on docs/en/examples.md
> +let combineFuture = future.asCombineFuture()
Это есть в демо-проекте разве что. В доке примера не встретил. Может быть и не пригодится никому, конечно, но мне не жалко) Обратную конвертацию вот решил сюда не добавлять, так как этот сценарий использования видится немного фантастичным.

2021-04-08 10:00 UTC, aapng requested changes

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +2. Откройте проект `app.xcodeproj` и задайте ваши ключи API в файле `Info.plist` проекта:
В README уже есть эта информация: притом более точная.

Поскольку эти файлы "не для гитхаба", то нужно оттуда скопировать актуальную инструкцию.

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +3. Дождитесь загрузки зависимостей Swift. Эта операция может занять длительное время.
```suggestion
3. Дождитесь загрузки зависимостей через SwiftPM. Эта операция может занять длительное время.
```

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +let apiKeys = APIKeys(directory: directoryAPIKey, map: mapAPIKey)
Ключи проверяются, поэтому прямо в примере можно написать `guard ... else { fatalError("API keys are empty or have incorrect format") }`.

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +
Раздели визуально (начни новый блок кода) и сделай подзаголовок. Тут непонятно, почему начинаешь по второму разу создавать контейнер.

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +// конфигурирование контейнера SDK
```suggestion
// Создание контейнера SDK с пользовательскими настройками.
```

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +#### Работа с потоками
```suggestion
#### Работа с отложенными результатами (Future) и потоками значений (Channel)
```

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +// получение объект справочника по идентификатору
```suggestion
// получение объекта справочника по идентификатору
```

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +let future = searchManager.searchByDirectoryObjectId(objectId: object.id)
Давай создадим в примере searchManager, чтобы пользователь лучше ориентировался. Давай считать, что у нас есть `self.sdk` (а значит `self.sdk.context`), потому что примеры в начале это покрывают.

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +// обработка результа поиска на главном потоке
Слово поток под iOS не сильно востребовано.

```suggestion
// обработка результата поиска в главной очереди
```

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +let searchDirectoryObjectCancellable = future.sink(
```suggestion
// Сохраняем результат вызова `sink`, так как его уничтожение обрывает подписку.
self.searchDirectoryObjectCancellable = future.sink(
```

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +#### Работа с потоками
До примеров нужно в одно предложение сказать, что обработчики Future и Channel по умолчанию вызываются на произвольной очереди, если документация не заявляет обратного. Кстати, сейчас случаев публично известной очереди нет.

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +	func sinkOnMainThread(
Я бы предпочёл `sinkOnMainQueue`, но раз уж так сложилось.

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +let searchDirectoryObjectCancellable = future.sinkOnMainThread(
```suggestion
self.searchDirectoryObjectCancellable = future.sinkOnMainThread(
```

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +			// Keep cancellable reference until either handler is called.
Неожиданно, что комментарий вдруг на английском. Пусть в примере будет перевод.

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +// получение объект справочника по идентификатору
```suggestion
// получение объекта справочника по идентификатору
```

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +// канал получения информации о прямоугольнике области просмотра
```suggestion
// Поток значений — прямоугольников видимой области карты.
// Значения будут присылаться при любом изменении видимой области до момента отписки.
```

2021-04-08 10:00 UTC, aapng commented on docs/en/examples.md
> +// с помощью расширения так же можно упростить работу с очередями
```suggestion
// с помощью расширения улучшаем интеграцию с `DispatchQueue`
```

2021-04-09 04:42 UTC, lagner commented on docs/en/examples.md
> +## Начало работы
Мы на встрече с документатом решили вообще убрать эту секцию из всех SDK. И для нативной и для WebGL. Хотим оставить ее только в README на github. Т.к. это все таки не обязательная часть работы с SDK.

2021-04-16 10:59 UTC, ktoto approved these changes

2021-04-16 10:59 UTC, merged