Update to NSDK v0.16.0
2gis/mobile-sdk-ios-demo pull request #40
Opened 2021-06-02 21:26 UTC by maxal9999

2021-06-03 03:44 UTC, t-artikov commented on docs/ru/changelog.md
> +- Добавлена возможность отключения анимации при появлении или исчезании объектов на карте через `MarkerOptions.animatedAppearance` и `Marker.setAnimatedAppearance`.
исчезании -> исчезновении

2021-06-03 03:48 UTC, t-artikov commented on docs/ru/changelog.md
> +- *Ломающее изменение*. Поддержана установка корректного DPI при создании карты. Теперь при установке DPI через `MapBuilder.setDevicePpi` необходимо задать множитель, который вычисляется как отношени
Это ведь все под капотом делается, в API нет класса MapBuilder. В описании должно быть как изменениние влияет на пользователя SDK.

2021-06-03 03:52 UTC, t-artikov commented on docs/ru/changelog.md
> +- Добавлена возможность отключения анимации при появлении или исчезании объектов на карте через `MarkerOptions.animatedAppearance` и `Marker.setAnimatedAppearance`.
исчезании -> исчезновении

2021-06-03 03:52 UTC, t-artikov commented on docs/ru/changelog.md
> +- *Ломающее изменение*. Поддержана установка корректного DPI при создании карты. Теперь при установке DPI через `MapBuilder.setDevicePpi` необходимо задать множитель, который вычисляется как отношени
Это ведь все под капотом делается, в API нет класса MapBuilder. В описании должно быть как изменениние влияет на пользователя SDK.

2021-06-03 06:37 UTC, maxal9999 commented on docs/ru/changelog.md
> +- *Ломающее изменение*. Поддержана установка корректного DPI при создании карты. Теперь при установке DPI через `MapBuilder.setDevicePpi` необходимо задать множитель, который вычисляется как отношени
Да, согласен. Тут нужно расписать через MapOptions.

2021-06-03 06:42 UTC, maxal9999 commented on docs/ru/changelog.md
> +- *Ломающее изменение*. Поддержана установка корректного DPI при создании карты. Теперь при установке DPI через `MapBuilder.setDevicePpi` необходимо задать множитель, который вычисляется как отношени
Поправил

2021-06-04 05:33 UTC, ok-gurov requested changes

2021-06-04 07:01 UTC, maxal9999 commented on docs/en/changelog.md
> +  `val geoPoint = GeoPoint(Arcdegree(1.0), Arcdegree(2.0))`
Да, тут согласен)

2021-06-04 07:01 UTC, maxal9999 commented on docs/en/changelog.md
> +  `val geoPoint = GeoPoint(1.0, 2.0)`.
А тут не согласен. Ты же перевел и GeoPoint, и Arcdegree на упрощенное создание, разве нет?

2021-06-04 07:07 UTC, maxal9999 commented on app/Views/Root/RootViewFactory.swift
>  		return SearchDemoView(
Ты имеешь ввиду передавать mapFactory, а не map? А почему так?

2021-06-04 07:22 UTC, aapng commented on docs/en/changelog.md
> +  `val geoPoint = GeoPoint(1.0, 2.0)`.
Олег предлагает указывать метки явно. Они обязательны. Arcdegree тут ни при чём. Как у тебя скомпилировалось?

2021-06-04 07:40 UTC, aapng requested changes

2021-06-04 07:40 UTC, aapng commented on app/Views/Root/RootViewFactory.swift
>  		return SearchDemoView(
Думаю, речь о том, что для viewFactory ниже уже создаётся mapFactory. Их не должно быть две.

2021-06-04 07:40 UTC, aapng commented on docs/en/changelog.md
> +- При создании объектов карты появилась возможность задавать порядок их отрисовки через `MarkerOptions.zIndex`, `PolygonOptions.zIndex` и т.д. Чем выше значение индекса, тем позднее объект появится н
Прошу переформулировать, чтобы было понятно, что это не какая-нибудь задержка в отрисовке с рисованием, а резрешение порядка наложения элементов. Наложение элементов — ключевые слова, по ним пользователь поймёт, зачем это нужно.

2021-06-04 07:40 UTC, aapng commented on docs/en/changelog.md
> +- Упрощение создания/преобразования простых типов данных, таких как `Arcdegree`, `Color`, `Elevation`, `GeoPoint` и т.д.
- Нужно объяснить суть упрощения. Что стало проще? Они и раньше просто создавались.
- Желательно перечислить все такие типы.

2021-06-04 07:40 UTC, aapng commented on docs/en/changelog.md
> +  `val geoPoint = GeoPoint(1.0, 2.0)`.
```suggestion
  `let geoPoint = GeoPoint(latitude: 54.0, longitude: 32.0)`.
```

2021-06-04 07:40 UTC, aapng commented on docs/en/changelog.md
> +  `val geoPoint = GeoPoint(latitude: Arcdegree(1.0), longitude: Arcdegree(2.0))`
Это Котлин. Нужно так:
```suggestion
  `let geoPoint = GeoPoint(latitude: Arcdegree(value: 54.0), longitude: Arcdegree(value: 32.0))`
```

2021-06-04 07:40 UTC, aapng commented on docs/en/changelog.md
> +- Добавлена возможность задавать список локалей в обход системным настройкам с помощью `LocaleManager.setOverridedLocales`. Для возврата системных локалей необходимо использовать `LocaleManager.reset
```suggestion
- Добавлена возможность задавать список локалей в обход системным настройкам с помощью `LocaleManager.setOverridedLocales`. Для возврата к системным локалям используется `LocaleManager.resetLocalesToSystemLocales`.
```

2021-06-04 07:40 UTC, aapng commented on docs/en/changelog.md
> +- Добавлен метод `toMapGeometry(trafficRoute, currentRoutePoint)` для получения геометрии оставшейся части маршрута.
Это Котлин.

2021-06-04 07:40 UTC, aapng commented on docs/en/changelog.md
> +- *Ломающее изменение*. Удален устаревший класс `MarkerBuilder` для создания объектов карты. Вместо него нужно использовать класс `MapObjectManager` для добавления объектов, а также `Marker`, `Polygo
```suggestion
- *Ломающее изменение*. Удален класс `MarkerBuilder` для создания объектов карты. Вместо него нужно использовать `MapObjectManager` для добавления объектов; конструкторы `Marker`, `Polygon` и пр. для их создания.
```

2021-06-04 07:40 UTC, aapng commented on docs/en/changelog.md
> +- *Ломающее изменение*. Поддержана установка корректного DPI при создании карты. Теперь помимо установки DPI через `MapOptions.devicePPI` можно задать `MapOptions.deviceDensity` - множитель, который
> Поддержана установка корректного DPI при создании карты.

Непонятно, чем предыдущая установка была некорректной.

> Теперь помимо установки DPI через `MapOptions.devicePPI` можно задать `MapOptions.deviceDensity` - множитель, который вычисляется как отношение устанавливаемого DPI к базовому DPI устройства.

Мы же автоматически вычисляем это значение при добавлении карты на экран, зачем его указывать снаружи? Будет ли это значение затёрто фактическим экранным?

2021-06-04 10:38 UTC, maxal9999 commented on docs/en/changelog.md
> +  `val geoPoint = GeoPoint(latitude: Arcdegree(1.0), longitude: Arcdegree(2.0))`
Блин, с val -> let вообще косяк, даже в глаза не бросилось (

2021-06-04 10:40 UTC, maxal9999 commented on docs/en/changelog.md
> +- Добавлен метод `toMapGeometry(trafficRoute, currentRoutePoint)` для получения геометрии оставшейся части маршрута.
https://stash.2gis.ru/projects/VN/repos/native-sdk/pull-requests/1195/diff#bindings/include/dgis/bindings/MapRouting.h
А вот нет. Для iOS эта штука также становится доступной.;

2021-06-04 10:51 UTC, maxal9999 commented on docs/en/changelog.md
> +  `val geoPoint = GeoPoint(1.0, 2.0)`.
А зачем тут добавлять latitude/longitude, если GeoPoint также умеет конструироваться на основе double?

2021-06-04 10:58 UTC, ok-gurov commented on app/Views/Root/RootViewFactory.swift
>  		return SearchDemoView(
Саджест почему-то тут не добавить(
```
return SearchDemoView(
    viewModel: viewModel,			
    viewFactory: self.makeDemoPageComponentsFactory(mapFactory:  mapFactory))	
}
```

2021-06-04 11:04 UTC, maxal9999 commented on docs/en/changelog.md
> +- *Ломающее изменение*. Поддержана установка корректного DPI при создании карты. Теперь помимо установки DPI через `MapOptions.devicePPI` можно задать `MapOptions.deviceDensity` - множитель, который
>зачем его указывать снаружи

Мы с Олегом подумали, что это может быть необходимо, если задается DPI для не основного окна.

2021-06-04 11:05 UTC, maxal9999 commented on docs/en/changelog.md
> +- *Ломающее изменение*. Поддержана установка корректного DPI при создании карты. Теперь помимо установки DPI через `MapOptions.devicePPI` можно задать `MapOptions.deviceDensity` - множитель, который
>Непонятно, чем предыдущая установка была некорректной.

Не учитывался nativeScale . СОбственно из того, что тут описано, это следует.

2021-06-04 11:14 UTC, maxal9999 commented on app/Views/Root/RootViewFactory.swift
>  		return SearchDemoView(
Да, я уже поправил. Теперь понял о чем речь.

2021-06-04 11:23 UTC, aapng commented on docs/en/changelog.md
> +- Добавлен метод `toMapGeometry(trafficRoute, currentRoutePoint)` для получения геометрии оставшейся части маршрута.
В Свифте будет так синтаксически: `toMapGeometry(trafficRoute:currentRoutePoint:)`.

И ещё пара вещей:
- Это не метод.
- Имя ужасное. Мы что-нибудь уже называли на to... в публичном интерфейсе?

2021-06-04 11:26 UTC, aapng commented on docs/en/changelog.md
> +- *Ломающее изменение*. Поддержана установка корректного DPI при создании карты. Теперь помимо установки DPI через `MapOptions.devicePPI` можно задать `MapOptions.deviceDensity` - множитель, который
> Не учитывался nativeScale . СОбственно из того, что тут описано, это следует.

Неочевидно. Да и непонятно из текста, почему это ломающее изменение: мол, добавилось новое свойство, которое автоматически принимает правильное значение.

> Мы с Олегом подумали, что это может быть необходимо, если задается DPI для не основного окна.

Вы праавильно подумали, но сейчас указывается DPI не основного окна (UIScreen.main), а того, на который кладётся карта. Или имеется в виду вообще произвольный DPI?

2021-06-04 11:33 UTC, maxal9999 commented on docs/en/changelog.md
> +- *Ломающее изменение*. Поддержана установка корректного DPI при создании карты. Теперь помимо установки DPI через `MapOptions.devicePPI` можно задать `MapOptions.deviceDensity` - множитель, который
>Неочевидно. Да и непонятно из текста, почему это ломающее изменение: мол, добавилось новое свойство, которое автоматически принимает правильное значение.

Насчет ломающего - согласен, оно скорее чинящее, уберу. 
Про саму опцию распишу подробнее тогда.

2021-06-04 11:34 UTC, maxal9999 commented on docs/en/changelog.md
> +- *Ломающее изменение*. Поддержана установка корректного DPI при создании карты. Теперь помимо установки DPI через `MapOptions.devicePPI` можно задать `MapOptions.deviceDensity` - множитель, который
> Или имеется в виду вообще произвольный DPI?

Да.

2021-06-04 11:56 UTC, ok-gurov approved these changes

2021-06-04 11:56 UTC, ok-gurov commented on docs/en/changelog.md
> +- Добавлена возможность задавать список локалей в обход системным настройкам с помощью `LocaleManager.setOverridedLocales`. Для возврата к системным локалям используется `LocaleManager.resetLocalesTo
Вметсто `LocaleManager.resetLocalesToSystemLocales` теперь передается пустой список в `LocaleManager.setOverridedLocales`

2021-06-04 12:57 UTC, aapng approved these changes

2021-06-04 12:57 UTC, aapng commented on docs/en/changelog.md
> +  Теперь доступен вариант конструирования `GeoPoint` на основе double.
```suggestion
  Теперь доступна инициализация `GeoPoint` из пары значений `CLLocationDegrees`.
```

2021-06-04 12:57 UTC, aapng commented on docs/en/changelog.md
> +- Добавлена возможность задавать список локалей в обход системным настройкам с помощью `LocaleManager.setOverridedLocales`. Для возврата к системным локалям необходимо передать пустой список в метод
```suggestion
- Добавлена возможность задавать список локалей в обход системных настроек с помощью `LocaleManager.setOverridedLocales`. Для возврата к системным локалям необходимо передать пустой список в метод `LocaleManager.setOverridedLocales`.
```

2021-06-04 12:57 UTC, aapng commented on docs/en/changelog.md
> +- Добавлена функция `toMapGeometry(trafficRoute:, currentRoutePoint:)` для получения геометрии оставшейся части маршрута.
Запятая не пишется.

```suggestion
- Добавлена функция `toMapGeometry(trafficRoute:currentRoutePoint:)` для получения геометрии оставшейся части маршрута.
```

2021-06-04 12:57 UTC, aapng commented on docs/en/changelog.md
> +- Поддержана установка корректного DPI при создании карты. Теперь помимо установки DPI через `MapOptions.devicePPI` можно задать `MapOptions.deviceDensity` - множитель, который вычисляется как отноше
> отношение устанавливаемого DPI к базовому DPI устройства

Очень непонятная фраза. Невозможно понять, что сюда устанавливать — только экспериментально подобрать. Смотри в чём проблема. У устройства ровно один DPI, поскольку в дюйме всегда одно и то же число миллиметров. Упоминание двух разных DPI вносит путаницу и попросту некорректно. Настоящий вопрос в том, как соотносятся разные виды точек.

Здесь нужно написать так: "множитель, равный числу физических пикселей устройства в одной логической точке экранной системы координат". Например, для заданного экрана (`UIScreen`) этот множитель равен значению `nativeScale`.

2021-06-04 13:24 UTC, merged